name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Kata dependencies
      run: dotnet restore IO2_TDD_Kata
    - name: Restore Tests dependencies
      run: dotnet restore Tests_for_IO2_TDD_Kata
    - name: Build Kata
      run: dotnet build IO2_TDD_Kata --no-restore
    - name: Build Tests
      run: dotnet build Tests_for_IO2_TDD_Kata --no-restore
    - name: Test
      run: dotnet test Tests_for_IO2_TDD_Kata --no-build --verbosity normal
